name: Optimize Images and Convert GIFs to WebP (no external actions)

on:
  push:
    branches:
      - main
    paths:
      - '**.png'
      - '**.jpg'
      - '**.jpeg'
      - '**.webp'
      - '**.gif'

jobs:
  optimize_and_convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install optimization tools
        run: |
          sudo apt update
          sudo apt install -y ffmpeg optipng jpegoptim gifsicle webp

      - name: Report File Sizes Before Optimization
        run: |
          echo "## 🧹 Original File Sizes" >> $GITHUB_STEP_SUMMARY
          find . -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.webp" -o -iname "*.gif" \) -exec du -h {} + | sort -h >> $GITHUB_STEP_SUMMARY

      - name: Optimize PNG, JPG, and WebP Files
        run: |
          find . -type f -iname "*.png" -exec optipng -o7 {} \;
          find . -type f -iname "*.jpg" -exec jpegoptim --strip-all --max=80 {} \;
          find . -type f -iname "*.jpeg" -exec jpegoptim --strip-all --max=80 {} \;
          find . -type f -iname "*.webp" -exec cwebp -q 80 {} -o {} \;

      - name: Convert GIFs to Animated WebP (keep originals)
        run: |
          find . -type f -iname "*.gif" | while read filename; do
            echo "Converting $filename to animated WebP..."
            ffmpeg -i "$filename" -loop 0 "${filename%.gif}.webp"
          done

      - name: Report File Sizes After Optimization
        run: |
          echo "## ✨ Optimized File Sizes" >> $GITHUB_STEP_SUMMARY
          find . -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.webp" -o -iname "*.gif" \) -exec du -h {} + | sort -h >> $GITHUB_STEP_SUMMARY

      - name: Commit Optimized and Converted Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Optimize images and convert GIFs to WebP" || echo "No changes to commit"
          git push
