name: Optimize Images to WebP

on:
  push:
    branches: [ main ] # Or your default branch
    paths:
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.tiff'
      - '**/*.tif'

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webp

      - name: Find and convert PNG/JPEG/TIFF to WebP
        run: |
          find . -regex '.*\.\(png\|jpe?g\|tiff?\) -print0' | while IFS= read -r -d $'\0' file; do
            output_file="${file%.*}.webp"
            echo "Converting $file to $output_file"
            cwebp "$file" -o "$output_file" # Adjust encoding settings as needed
          done

      - name: Find and convert GIF to WebP
        run: |
          find . -name "*.gif" -print0 | while IFS= read -r -d $'\0' file; do
            output_file="${file%.gif}.webp"
            echo "Converting $file to $output_file"
            gif2webp "$file" -o "$output_file" # Adjust encoding settings as needed
          done

      - name: Commit changes (Optional)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Optimize images to WebP"
          push_options: '--force-with-lease'