name: Convert Static Images to AVIF

on:
  push:
    paths:
      - '**.png'
      - '**.jpg'
      - '**.jpeg'
    branches: [ main, master ]
  pull_request:
    paths:
      - '**.png'
      - '**.jpg'
      - '**.jpeg'
  workflow_dispatch:

# Add permissions block to allow writing to the repository
permissions:
  contents: write

jobs:
  convert-static-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install AVIF tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libavif-bin
      
      - name: Convert PNG files to AVIF
        run: |
          find . -type f -name "*.png" | while read file; do
            avif_file="${file%.png}.avif"
            echo "Converting $file to $avif_file"
            avifenc --min 0 --max 63 --speed 6 --jobs 2 "$file" "$avif_file"
          done
      
      - name: Convert JPG/JPEG files to AVIF
        run: |
          find . -type f \( -name "*.jpg" -o -name "*.jpeg" \) | while read file; do
            if [[ "$file" == *.jpg ]]; then
              avif_file="${file%.jpg}.avif"
            else
              avif_file="${file%.jpeg}.avif"
            fi
            echo "Converting $file to $avif_file"
            avifenc --min 0 --max 63 --speed 6 --jobs 2 "$file" "$avif_file"
          done
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "*.avif"
          git diff --quiet && git diff --staged --quiet || (git commit -m "Convert static images to AVIF format [skip ci]" && git push)